hibernate.connection.url=jdbc:mysql://localhost:3306/wigell_rental_db?createDatabaseIfNotExist=true&useSSL=false
hibernate.connection.username=
hibernate.connection.password=
hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.dialect=org.hibernate.dialect.MySQLDialect

# "update" creates tables if they don't exist, and updates them if you change the code

hibernate.hbm2ddl.auto=update
hibernate.show_sql=true
hibernate.format_sql=true